

var quotesDisplay = [
    '"The more you sweat in training, the less you bleed in combat." – Navy SEALs',
    '"The ultimate aim of martial arts is not having to use them." – Miyamoto Musashi',
    '"I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times." – Bruce Lee',
    '"It does not matter how slowly you go as long as you do not stop." – Confucius',
    '"In the martial arts, it is not how much you have learned, but how much you have absorbed from what you have learned." – Bruce Lee',
    '"To win one hundred victories in one hundred battles is not the highest skill. To subdue the enemy without fighting is the highest skill." – Sun Tzu',
    '"Martial arts is not about fighting; it is about building character." – Bo Bennett',
    '"In martial arts, the biggest opponent you will ever face is yourself." – Unknown',
    '"True martial artists do not fight to win, they fight to better themselves." – Unknown',
    '"Karate is not about techniques and their execution, but about perfecting ones character." – Funakoshi',
    '"Martial arts begin and end with respect." – Unknown',
    '"A black belt is a white belt who never quit." – Unknown',
    '"The best fighter is never angry." – Lao Tzu',
    '"Martial arts is not about being better than someone else, its about being better than you used to be." – Unknown',
    '"The stillness in stillness is not the real stillness; only when there is stillness in movement does the universal rhythm manifest." – Bruce Lee',
    '"In the martial arts, introspection begets wisdom. Always see contemplation on your actions as an opportunity to improve." – Soke Behzad Ahmadi',
    '"A true martial artist doesnt live in balance; he creates it."  – Dan Millman',
    '"Your body can stand almost anything. Its your mind you have to convince." – Unknown',
    '"The successful warrior is the average person, with laser-like focus." – Bruce Lee',
    '"Martial arts are a vehicle for developing your human potential." – Joe Rogan',
    '"Train with the energy of a warrior and soon you will have the heart of a warrior." – Shifu Yan Lei',
    '"Martial arts are less about fighting others and more about fighting ourselves. The real value lies in conquering ones own limitations." – Unknown',
    '"In life, unlike chess, the game continues after checkmate." – Isaac Asimov',
    '"A punch should stay like a treasure in the sleeve. It should not be used indiscriminately." – Chotoku Kyan',
    '"In martial arts, the journey is the reward." – Unknown',
    '"Be humble, hungry, and always be the hardest worker in the room." – Dwayne ‘The Rock’ Johnson',
    '"My mom is always telling me it takes a long time to get to the top, but a short time to get to the bottom." – Miley Cyrus',
    '"Try and fail, but never fail to try." – Jared Leto',
    '"He who has the gold makes the rules." – Tyler Perry',
    '"Without wonder and insight, acting is just a business. With it, it becomes creation." – Bette Davis',
  ];

  export default quotesDisplay;